;; DGO definition file for Awful Village level
;; We use the convention of having a longer DGO name for levels without precomputed visibility.

;; the actual file name still needs to be 8.3
("OVG.DGO"
 ("static-screen.o"
  "test-zone-obs.o"
  "jungle-obs.o"
  "jungleb-obs.o"
  "sunken-water.o"
  "training-part.o"
  "overgrown-part.o"
  "villagep-obs.o"
  "village1-part.o"
  "village1-part2.o"
  "village-obs.o"
  "aphid.o"
  "bouncer.o"
  ;;"muse.o"
  "junglefish.o"
  "hopper.o"
  "junglesnake.o"
  "kermit.o"
  "lurkercrab.o"
  "lurkerpuppy.o"
  "plat-button-ag.go"
  "generic-button-ag.go"
  "warp-gate-switch-ag.go"
  "babak-ag.go"
  "kermit-ag.go"
  "hopper-ag.go"
  "aphid-lurker-ag.go"
  "junglesnake-ag.go"
  "junglefish-ag.go"
  "muse-ag.go"
  "plat-eco-ag.go"
  "eichar-pole+0-ag.go"
  "orb-cache-top-ag.go"
  "bounceytarp-ag.go"
  "plat-ag.go"
  "test-actor-ag.go"
  "water-anim-jungle-ag.go"
  "water-anim-sunken-ag.go"
  "jng-iris-door-ag.go"
  "overgrown.go"
 ))
